default: &default
  host: localhost
  port: 6379
development:
  <<: *default
  db: 0
  namespace: immedia_development
test:
  <<: *default
  db: 1
  namespace: immedia_test
staging:
  <<: *default
  db: 2
  namespace: immedia_staging
uat:
  <<: *default
  db: 2
  namespace: immedia_uat
production:
  <<: *default
  db: 3
  namespace: immedia_production
