HOST: http://0.0.0.0:3000
DEFAULT_EMAIL_RECIPIENTS:
  - siphom@mytopdog.com

# available options :file, :fog
UPLOAD_STORAGE_TYPE: :file
PERFORM_ASYNC: false
WISPER_CLASS_SUBSCRIBE_ASYNC: false
LOG_OBSERVER_SETTING: true
# available options : deliver_now or deliver_later
MAIL_DELIVERY_METHOD: :deliver_now
AWS:
  AWS_ACCESS_KEY_ID: CHANGE ME
  AWS_SECRET_ACCESS_KEY: CHANGE ME
  AWS_BUCKET: immedia_development

SMTP_SETTINGS:
  address: localhost
  port: 1025

EXCEPTION_SMTP_SETTINGS:
  address: localhost
  port: 1025

SYSTEM_ADMIN_DATA:
  email: sa@an.com
  password: password
  password_confirmation: password

SYSTEM_ADMIN_PROFILE_DATA:
  firstname: Super System
  lastname: Admin User
  gender: Male
  birthdate: <%= 30.years.ago %>

app_id: IK1JDMETUJCSU2RQOT3SSDWJKSVWWMRFSSEIFIFVRYESNJCH
app_secret: JI44B0P4LXAWNUNCOYNMAANTFOM2OKADZC2VNQHLHOH3FIGJ

instagram_client_id: 5f91223a60e34ed2ba9dd2db78f4cfc1
#instagram_access_token: 19fcb5be169a4155b6456f3f970199ac
instagram_access_token: 3412951647.1677ed0.2f37f548edea4b1087f32f94108da503
