HOST: http://immedia.co.za
DEFAULT_EMAIL_RECIPIENTS:
  - siphom@mytopdog.com
# available options :file, :fog
UPLOAD_STORAGE_TYPE: :file
PERFORM_ASYNC: false
WISPER_CLASS_SUBSCRIBE_ASYNC: false
LOG_OBSERVER_SETTING: true
# available options : deliver_now or deliver_later
MAIL_DELIVERY_METHOD: :deliver_later
AWS:
  AWS_ACCESS_KEY_ID: CHANGE ME
  AWS_SECRET_ACCESS_KEY: CHANGE ME
  AWS_BUCKET: immedia_production


# # OWN SERVER EXAMPLE
SMTP_SETTINGS:
  address: smtp.immedia.co.za
  port: 587
  user_name: communication@immedia.co.za
  password: immedia123!!
  authentication: 'plain'
  enable_starttls_auto: true
  openssl_verify_mode: none

EXCEPTION_SMTP_SETTINGS:
  address: smtp.immedia.co.za
  port: 587
  user_name: communication@immedia.co.za
  password: immedia123!!
  authentication: 'plain'
  enable_starttls_auto: true
  openssl_verify_mode: none

SYSTEM_ADMIN_DATA:
  email: sa@an.com
  password: password
  password_confirmation: password

SYSTEM_ADMIN_PROFILE_DATA:
  firstname: Super System
  lastname: Admin User
  gender: Male
  birthdate: <%= 30.years.ago %>
app_id: ULRETEXRBDVZOEPKSO2PM52OHKZUPMDQUPJDV1NS02I4JONA
app_secret: WHRTH1LZUOGJ1Q1ULTKOP1ST3A45QFAOLRDMFVN4AYSTRUWR

instagram_client_id: b0209cce731b419787f6b12cad7baad3
instagram_access_token_1: 19fcb5be169a4155b6456f3f970199ac
instagram_access_token: 3412951647.1677ed0.2f37f548edea4b1087f32f94108da503
